/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SeriesList 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4671987836344886638L;
    private int available;
    private String collectionURI;
    private List<SeriesSummary> items;
    private int returned;
    /** GETTER
     * The number of total available series in this list. Will always be greater than or equal to the "returned" value.
     */
    @JsonGetter("available")
    public int getAvailable ( ) { 
        return this.available;
    }
    
    /** SETTER
     * The number of total available series in this list. Will always be greater than or equal to the "returned" value.
     */
    @JsonSetter("available")
    public void setAvailable (int value) { 
        this.available = value;
        notifyObservers(this.available);
    }
 
    /** GETTER
     * The path to the full list of series in this collection.
     */
    @JsonGetter("collectionURI")
    public String getCollectionURI ( ) { 
        return this.collectionURI;
    }
    
    /** SETTER
     * The path to the full list of series in this collection.
     */
    @JsonSetter("collectionURI")
    public void setCollectionURI (String value) { 
        this.collectionURI = value;
        notifyObservers(this.collectionURI);
    }
 
    /** GETTER
     * The list of returned series in this collection.
     */
    @JsonGetter("items")
    public List<SeriesSummary> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * The list of returned series in this collection.
     */
    @JsonSetter("items")
    public void setItems (List<SeriesSummary> value) { 
        this.items = value;
        notifyObservers(this.items);
    }
 
    /** GETTER
     * The number of series returned in this collection (up to 20).
     */
    @JsonGetter("returned")
    public int getReturned ( ) { 
        return this.returned;
    }
    
    /** SETTER
     * The number of series returned in this collection (up to 20).
     */
    @JsonSetter("returned")
    public void setReturned (int value) { 
        this.returned = value;
        notifyObservers(this.returned);
    }
 
}
 